spring:
  application:
    name: SPRING-BOOT-APPLICATION
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tuliu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.tuliu.translate.entity
platform:
  key: 7e8968fe8fe6b4ae9f724814d148626b
server:
  port: 8001
  max-http-header-size: 1024000
